Add arm64 prebuild for Apple Silicon
macOS developers on Apple Silicon need to recompile ffi-napi right now because:

>Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=93 uv=1 armv=8 libc=glibc node=16.7.0
>    loaded from: node_modules/ref-napi
>
>    at Function.load.path (node_modules/node-gyp-build/index.js:59:9)

I'm just following the example in #78 so I'm not sure if this actually does the right thing!